
[functions.send-whatsapp-reminder]
enabled = true
verify_jwt = false
import_map = "./functions/send-whatsapp-reminder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-whatsapp-reminder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-whatsapp-reminder/*.html" ]

[functions.whatsapp-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/whatsapp-webhook/deno.json"
entrypoint = "./functions/whatsapp-webhook/index.ts"

[functions.whatsapp-message-status]
enabled = true
verify_jwt = false
import_map = "./functions/whatsapp-message-status/deno.json"
entrypoint = "./functions/whatsapp-message-status/index.ts"
